groups:
- name: namada-validator-alerts
  rules:
  - alert: NamadaBlockHeightStalled
    expr: increase(namada_block_height[1m]) == 0
    labels:
      severity: critical
    annotations:
      summary: "Namada block height is not increasing"
      description: "The validators at {{ $labels.instance }} appears to be stalled as the block height has not increased for 5 minutes. Last recorded block height: {{ with query \"namada_block_height\" }}{{ printf \"%.0f\" (. | first | value)}}{{ end }} "

  - alert: NamadaBlockProcessingSlow
    expr: rate(namada_block_time_sum[5m]) / rate(namada_block_time_count[5m]) > 10
    labels:
      severity: warning
    annotations:
      summary: "Namada block processing time is slow"
      description: "The average block processing time has exceeded 10 seconds considering the the last 5 minutes of data. Block height: {{ with query \"namada_block_height\" }}{{ printf \"%.0f\" (. | first | value)}}{{ end }}"

  - alert: NamadaVotingPowerConcentration
    expr: namada_one_third_threshold > 0.6 * namada_two_third_threshold
    labels:
      severity: critical
    annotations:
      summary: "Low validator participation detected"
      description: "The number of validators needed for 1/3 of the voting power if more than half the number of validators nded for 2/3 voting power. Block height: {{ with query \"namada_block_height\" }}{{ printf \"%.0f\" (. | first | value)}}{{ end }}"

  - alert: NamadaLowValidatorParticipation
    expr: namada_one_third_threshold < 1 or namada_two_third_threshold < 1
    labels:
      severity: critical
    annotations:
      summary: "Low validator participation detected"
      description: "The number of validators needed for 1/3 or 2/3 consensus is at zero, which indicates a potential network failure. Block height: {{ with query \"namada_block_height\" }}{{ printf \"%.0f\" (. | first | value)}}{{ end }}"

  - alert: NamadaAbnormalBonding
    expr: rate(namada_bonds_per_epoch[10m]) > 1.5 * avg_over_time(namada_bonds_per_epoch[7d])
    labels:
      severity: warning
    annotations:
      summary: "Unusual increase in bonding activity"
      description: "Bonding per epoch has increased significantly over the last 10 minutes compared to the average of last 7 days. Block height: {{ with query \"namada_block_height\" }}{{ printf \"%.0f\" (. | first | value)}}{{ end }}"

  - alert: NamadaAbnormalUnbonding
    expr: rate(namada_unbonds_per_epoch[10m]) > 1.5 * avg_over_time(namada_unbonds_per_epoch[7d])
    labels:
      severity: warning
    annotations:
      summary: "Unusual increase in unbonding activity"
      description: "Unbonding per epoch has increased significantly over the last 10 minutes compared to the average of last 7 days. Block height: {{ with query \"namada_block_height\" }}{{ printf \"%.0f\" (. | first | value)}}{{ end }}"

  - alert: NamadaTransactionBatchSpike
    expr: |
      rate(namada_transaction_batch_size_count[10m])
      > (2 * quantile(0.50, rate(namada_transaction_batch_size_count[7d])))
    labels:
      severity: warning
    annotations:
      summary: "Spike in transaction batch size"
      description: "Transaction batching has significantly increased over the last 10 minutes compared to the 7-day median. Block height: {{ with query \"namada_block_height\" }}{{ printf \"%.0f\" (. | first | value)}}{{ end }}"
        
  - alert: HighTransactionFeesAnomaly
    expr: |
      (increase(namada_fees[10m]) / increase(namada_block_height[10m]))
      > (
          avg_over_time(namada_fees[10m]) / avg_over_time(namada_block_height[10m])
          + 2 * stddev_over_time(namada_fees[10m]) / avg_over_time(namada_block_height[10m])
        )
    labels:
      severity: warning
    annotations:
      summary: "Anomalous Transaction Fees"
      description: "Transaction fees per block exceeded normal range. Current: {{ $value }} NAM. Expected: < {{ with query \"avg_over_time(namada_fees[10m]) + 2 * stddev_over_time(namada_fees[10m])\" }}{{ printf \"%.2f\" (. | first | value)}}{{ end }}."
  - alert: HighTransactionFeesAvg
    expr: sum(fees_counter) > 2 * sum(avg_over_time(fees_counter[10m]))
    labels:
      severity: warning
    annotations:
      summary: "Unusual Transaction Fees Detected - 10m Average"
      description: "Transaction fees in block {{ $labels.height }} are unusually high (comapred with recent 10m average). Current: {{ $value }} NAM. Block height: {{ with query \"namada_block_height\" }}{{ printf \"%.0f\" (. | first | value)}}{{ end }}"
  
  - alert: AbnormalInnerTransactionFailureRate
    expr: |
      (rate(namada_transaction_kind{failed="true"}[10m]) / rate(namada_transaction_kind[10m]))
      >
      (2 * quantile(0.50, rate(namada_transaction_kind{failed="true"}[7d:]) / rate(namada_transaction_kind[7d:])))
    labels:
      severity: critical
    annotations:
      summary: "Unusual spike in inner transaction failures"
      description: |
        The failure rate of inner transactions has spiked abnormally.
        Current failure rate: {{ $value }}
        This is **more than 2x the historical median** failure rate over the past 7 days.
        Block height: {{ with query "namada_block_height" }}{{ printf "%.0f" (. | first | value) }}{{ end }}
        
  - alert: WhaleTransactionDetected
    expr: |
      transfer_amount > 10 * quantile(0.50, avg_over_time(transfer_amount[7d])) by (token)
      #### 2 std dev from
    labels:
      severity: warning
    annotations:
      summary: "Potential Whale Detected in {{ $labels.token }}"
      description: |
        A large transfer was detected in {{ $labels.token }}.
        Transfer Amount: {{ $value }} {{ $labels.token }}
        This exceeds 2x the **median** transfer amount in the last 7 days.
        Block height: {{ with query "namada_block_height" }}{{ printf "%.0f" (. | first | value) }}{{ end }}

  - alert: HighSlashingRate
    expr: |
      slashes > 0
    labels:
      severity: critical
    annotations:
      summary: "Unusual number of validator slashes"
      description: |
        The slashing rate is abnormally high—more than twice the median of the last 7 days.
        This could indicate a network issue or malicious behavior. 
        Block height: {{ with query "namada_block_height" }}{{ printf "%.0f" (. | first | value) }}{{ end }}
