groups:
- name: namada-validator-alerts
  rules:
  - alert: NamadaBlockHeightStalled
    expr: increase(namada_block_height[1m]) == 0
    labels:
      severity: critical
    annotations:
      summary: "Namada block height is not increasing"
      description: "The validators at {{ $labels.instance }} appears to be stalled as the block height has not increased for 5 minutes. Last recorded block height: {{ with query \"namada_block_height\" }}{{ printf \"%.0f\" (. | first | value)}}{{ end }} "

  - alert: NamadaBlockProcessingSlow
    expr: rate(namada_block_time_sum[5m]) / rate(namada_block_time_count[5m]) > 10
    labels:
      severity: warning
    annotations:
      summary: "Namada block processing time is slow"
      description: "The average block processing time has exceeded 10 seconds considering the the last 5 minutes of data. Block height: {{ with query \"namada_block_height\" }}{{ printf \"%.0f\" (. | first | value)}}{{ end }}"

  - alert: NamadaVotingPowerConcentration
    expr: namada_one_third_threshold > 0.6 * namada_two_third_threshold
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Low validator participation detected"
      description: "The number of validators needed for 1/3 of the voting power if more than half the number of validators nded for 2/3 voting power. Block height: {{ with query \"namada_block_height\" }}{{ printf \"%.0f\" (. | first | value)}}{{ end }}"

  - alert: NamadaLowValidatorParticipation
    expr: namada_one_third_threshold < 1 or namada_two_third_threshold < 1
    labels:
      severity: critical
    annotations:
      summary: "Low validator participation detected"
      description: "The number of validators needed for 1/3 or 2/3 consensus is at zero, which indicates a potential network failure. Block height: {{ with query \"namada_block_height\" }}{{ printf \"%.0f\" (. | first | value)}}{{ end }}"

  - alert: NamadaAbnormalBonding
    expr: rate(namada_bonds_per_epoch[10m]) > 1.5 * avg_over_time(namada_bonds_per_epoch[7d])
    labels:
      severity: warning
    annotations:
      summary: "Unusual increase in bonding activity"
      description: "Bonding per epoch has increased significantly over the last 10 minutes compared to the average of last 7 days. Block height: {{ with query \"namada_block_height\" }}{{ printf \"%.0f\" (. | first | value)}}{{ end }}"

  - alert: NamadaAbnormalUnbonding
    expr: rate(namada_unbonds_per_epoch[10m]) > 1.5 * avg_over_time(namada_unbonds_per_epoch[7d])
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Unusual increase in unbonding activity"
      description: "Unbonding per epoch has increased significantly over the last 10 minutes compared to the average of last 7 days. Block height: {{ with query \"namada_block_height\" }}{{ printf \"%.0f\" (. | first | value)}}{{ end }}"

  - alert: NamadaZeroTransactionBatches
    expr: namada_transaction_batch_size_count == 0
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: "No transaction batches processed"
      description: "No transactions have been batched for the last 10 minutes, which might indicate network inactivity. Block height: {{ with query \"namada_block_height\" }}{{ printf \"%.0f\" (. | first | value)}}{{ end }}"

  - alert: NamadaPeerCountLow
    expr: count(namada_peers) < 10
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Namada peer count is critically low!"
      description: "The number of active Namada peers has dropped below 10 for more than 5 minutes. This may indicate network instability or a partition issue. Block height: {{ with query \"namada_block_height\" }}{{ printf \"%.0f\" (. | first | value)}}{{ end }}"

  - alert: NamadaPeerCountDrop
    expr: count(namada_peers) < quantile(0.5, count_over_time(namada_peers[10m])) - 10
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: "Sudden drop in Namada peer count"
      description: |
        The number of active Namada peers dropped significantly in the last 10 minutes.
        Previous 10min median: {{ with query "quantile(0.5, count_over_time(namada_peers[10m]))" }}{{ printf "%.0f" (. | first | value)}}{{ end }}
        Current count: {{ with query "count(namada_peers)" }}{{ printf "%.0f" (. | first | value)}}{{ end }}
        Block height: {{ with query "namada_block_height" }}{{ printf "%.0f" (. | first | value)}}{{ end }}
        

  - alert: NamadaNoPeers
    expr: count(namada_peers) == 0
    for: 30m
    labels:
      severity: critical
    annotations:
      summary: "Namada has no active peers!"
      description: "There are currently no active peers connected to Namada. This might indicate a network outage or severe connectivity issues. Block height: {{ with query \"namada_block_height\" }}{{ printf \"%.0f\" (. | first | value)}}{{ end }}"

  - alert: HighTransactionFees
    expr: namada_fees > 10
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "High Transaction Fees Detected - Threshold"
      description: "Total transaction fees in block {{ $labels.height }} exceeded the threshold. Current value: {{ $value }} NAM. Block height: {{ with query \"namada_block_height\" }}{{ printf \"%.0f\" (. | first | value)}}{{ end }}"

  - alert: HighTransactionFeesAvg
    expr: sum(fees_counter) > 2 * sum(avg_over_time(fees_counter[10m]))
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "Unusual Transaction Fees Detected - 10m Average"
      description: "Transaction fees in block {{ $labels.height }} are unusually high (comapred with recent 10m average). Current: {{ $value }} NAM. Block height: {{ with query \"namada_block_height\" }}{{ printf \"%.0f\" (. | first | value)}}{{ end }}"
  
  - alert: AbnormalInnerTransactionFailureRate
    expr: |
      (rate(namada_transaction_kind{failed="true"}[10m]) / rate(namada_transaction_kind[10m]))
      >
      (2 * quantile(0.50, rate(namada_transaction_kind{failed="true"}[7d:]) / rate(namada_transaction_kind[7d:])))
    labels:
      severity: critical
    annotations:
      summary: "Unusual spike in inner transaction failures"
      description: |
        The failure rate of inner transactions has spiked abnormally.
        Current failure rate: {{ $value }}
        This is **more than 2x the historical median** failure rate over the past 7 days.
        Block height: {{ with query "namada_block_height" }}{{ printf "%.0f" (. | first | value) }}{{ end }}
        
  - alert: WhaleTransactionDetected
    expr: |
      transfer_amount > 2 * quantile(0.50, avg_over_time(transfer_amount[7d])) by (token)
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "Potential Whale Detected in {{ $labels.token }}"
      description: |
        A large transfer was detected in {{ $labels.token }}.
        Transfer Amount: {{ $value }} {{ $labels.token }}
        This exceeds 2x the **median** transfer amount in the last 7 days.
        Block height: {{ with query "namada_block_height" }}{{ printf "%.0f" (. | first | value) }}{{ end }}

  - alert: HighSlashingRate
    expr: |
      rate(slashes[10m]) > 2 * quantile(0.50, rate(slashes[7d]))
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Unusual number of validator slashes"
      description: |
        The slashing rate is abnormally high—more than twice the median of the last 7 days.
        This could indicate a network issue or malicious behavior. 
        Block height: {{ with query "namada_block_height" }}{{ printf "%.0f" (. | first | value) }}{{ end }}