groups:
- name: namada-validator-alerts
  rules:
  - alert: NamadaBlockHeightStalled
    expr: increase(namada_block_height{ chain_id="namada.5f5de2dd1b88cba30586420" }[1m]) == 0
    labels:
      severity: critical
    annotations:
      summary: "Namada block height is not increasing"
      description: |
          The validators at {{ $labels.chain_id }} appears to be stalled as the block height has not increased for 5 minutes. 
          Last recorded block height: {{ with query "namada_block_height{chain_id=\"namada.5f5de2dd1b88cba30586420\"}" }} {{ printf "%.0f" (. | first | value)}}{{ end }}

  - alert: NamadaBlockProcessingSlow
    expr: rate(namada_block_time_sum[5m]) / rate(namada_block_time_count[5m]) > 10
    labels:
      severity: warning
    annotations:
      summary: "Namada block processing time is slow"
      description: |
        The average block processing time has exceeded 10 seconds considering the the last 5 minutes of data. 
        Block height: {{ with query "namada_block_height{chain_id=\"namada.5f5de2dd1b88cba30586420\"}" }}{{ printf "%.0f" (. | first | value)}}{{ end }}. 
        Chain id: {{ $labels.chain_id }}

  - alert: NamadaVotingPowerConcentration
    expr: namada_one_third_threshold{ chain_id="namada.5f5de2dd1b88cba30586420" } > 0.6 * namada_two_third_threshold{ chain_id="namada.5f5de2dd1b88cba30586420" }
    labels:
      severity: critical
    annotations:
      summary: "Low validator participation detected"
      description: |
        The number of validators needed for 1/3 of the voting power if more than half the number of validators nded for 2/3 voting power. 
        Block height: {{ with query "namada_block_height{ chain_id=\"namada.5f5de2dd1b88cba30586420\" }" }}{{ printf "%.0f" (. | first | value)}}{{ end }}
        Chain id: {{ $labels.chain_id }}

  - alert: NamadaLowValidatorParticipation
    expr: namada_one_third_threshold{ chain_id="namada.5f5de2dd1b88cba30586420" } < 1 or namada_two_third_threshold{ chain_id="namada.5f5de2dd1b88cba30586420" } < 1
    labels:
      severity: critical
    annotations:
      summary: "Low validator participation detected"
      description: |
        The number of validators needed for 1/3 or 2/3 consensus is at zero, which indicates a potential network failure. 
        Block height: {{ with query "namada_block_height{ chain_id=\"namada.5f5de2dd1b88cba30586420\" }" }}{{ printf "%.0f" (. | first | value)}}{{ end }}
        Chain id: {{ $labels.chain_id }}

  - alert: NamadaAbnormalBonding
    expr: rate(namada_bonds_per_epoch{ chain_id="namada.5f5de2dd1b88cba30586420" }[10m]) > 1.5 * avg_over_time(namada_bonds_per_epoch{ chain_id="namada.5f5de2dd1b88cba30586420" }[7d])
    labels:
      severity: warning
    annotations:
      summary: "Unusual increase in bonding activity"
      description: |
        Bonding per epoch has increased significantly over the last 10 minutes compared to the average of last 7 days. 
        Block height: {{ with query "namada_block_height{ chain_id=\"namada.5f5de2dd1b88cba30586420\" }" }}{{ printf "%.0f" (. | first | value)}}{{ end }}
        Chain id: {{ $labels.chain_id }}


  - alert: NamadaAbnormalUnbonding
    expr: rate(namada_unbonds_per_epoch{ chain_id="namada.5f5de2dd1b88cba30586420" }[10m]) > 1.5 * avg_over_time(namada_unbonds_per_epoch{ chain_id="namada.5f5de2dd1b88cba30586420" }[7d])
    labels:
      severity: warning
    annotations:
      summary: "Unusual increase in unbonding activity"
      description: |
        Unbonding per epoch has increased significantly over the last 10 minutes compared to the average of last 7 days.
        Block height: {{ with query "namada_block_height{ chain_id=\"namada.5f5de2dd1b88cba30586420\" }" }}{{ printf "%.0f" (. | first | value)}}{{ end }}
        Chain id: {{ $labels.chain_id }}

  - alert: NamadaTransactionBatchSpike
    expr: |
      rate(namada_transaction_batch_size_count{ chain_id="namada.5f5de2dd1b88cba30586420" }[10m]) > (2 * quantile(0.50, rate(namada_transaction_batch_size_count[7d])))
    labels:
      severity: warning
    annotations:
      summary: "Spike in transaction batch size"
      description: |
        Transaction batching has significantly increased over the last 10 minutes compared to the 7-day median. 
        Block height: {{ with query "namada_block_height{ chain_id=\"namada.5f5de2dd1b88cba30586420\" }" }}{{ printf "%.0f" (. | first | value)}}{{ end }}
        Chain id: {{ $labels.chain_id }}
        
  - alert: HighTransactionFeesAnomaly
    expr: |
      (sum by (token) (increase(namada_fees{ chain_id="namada.5f5de2dd1b88cba30586420" }[10m])) / increase(namada_block_height{ chain_id="namada.5f5de2dd1b88cba30586420" }[10m])) 
      > (
          sum by (token) (avg_over_time(namada_fees{ chain_id="namada.5f5de2dd1b88cba30586420" }[10m])) / avg_over_time(namada_block_height{ chain_id="namada.5f5de2dd1b88cba30586420" }[10m]) 
          + 2 * sum by (token) (stddev_over_time(namada_fees{ chain_id="namada.5f5de2dd1b88cba30586420" }[10m])) / avg_over_time(namada_block_height{ chain_id="namada.5f5de2dd1b88cba30586420" }[10m])
        )
    labels:
      severity: warning
    annotations:
      summary: "Anomalous Transaction Fees for Token {{ $labels.token }}"
      description: |
        Transaction fees per block for token {{ $labels.token }} have exceeded the expected range. 
        Current: {{ $value }} NAM. 
        Expected: < {{ with query "sum by (token) (avg_over_time(namada_fees{ chain_id=\"namada.5f5de2dd1b88cba30586420\" }[10m])) + 2 * sum by (token) (stddev_over_time(namada_fees{ chain_id=\"namada.5f5de2dd1b88cba30586420\" }[10m]))" }}{{ printf "%.2f" (. | first | value)}}{{ end }} NAM.
        Chain id: {{ $labels.chain_id }}

  - alert: HighTransactionFeesAvg
    expr: |
      (sum by (token) (increase(namada_fees{ chain_id="namada.5f5de2dd1b88cba30586420" }[10m])) / increase(namada_block_height{ chain_id="namada.5f5de2dd1b88cba30586420" }[10m]))
      > (
          scalar(sum by (token) (avg_over_time(namada_fees{ chain_id="namada.5f5de2dd1b88cba30586420" }[10m]))) / scalar(avg_over_time(namada_block_height{ chain_id="namada.5f5de2dd1b88cba30586420" }[10m]))
          + 2 * scalar(sum by (token) (stddev_over_time(namada_fees{ chain_id="namada.5f5de2dd1b88cba30586420" }[10m]))) / scalar(avg_over_time(namada_block_height{ chain_id="namada.5f5de2dd1b88cba30586420" }[10m]))
        )
    labels:
      severity: warning
    annotations:
      summary: "Unusual Transaction Fees for Token {{ $labels.token }}"
      description: |
        Transaction fees per block for token {{ $labels.token }} are unusually high. 
        Current: {{ $value }} NAM. 
        Expected: < {{ with query "scalar(sum by (token) (avg_over_time(namada_fees{ chain_id=\"namada.5f5de2dd1b88cba30586420\" }[10m]))) + 2 * scalar(sum by (token) (stddev_over_time(namada_fees{ chain_id=\"namada.5f5de2dd1b88cba30586420\" }[10m])))" }}{{ printf "%.2f" (. | first | value)}}{{ end }} NAM.
        Chain id: {{ $labels.chain_id }}

  - alert: AbnormalInnerTransactionFailureRate
    expr: |
      (rate(namada_transaction_kind{chain_id="namada.5f5de2dd1b88cba30586420", failed="true"}[10m]) / rate(namada_transaction_kind{ chain_id="namada.5f5de2dd1b88cba30586420" }[10m]))
      >
      (2 * quantile(0.50, rate(namada_transaction_kind{chain_id="namada.5f5de2dd1b88cba30586420", failed="true"}[7d:]) / rate(namada_transaction_kind{chain_id="namada.5f5de2dd1b88cba30586420"}[7d:])))
    labels:
      severity: critical
    annotations:
      summary: "Unusual spike in inner transaction failures"
      description: |
        The failure rate of inner transactions has spiked abnormally.
        Current failure rate: {{ $value }}
        This is **more than 2x the historical median** failure rate over the past 7 days.
        Block height: {{ with query "namada_block_height{chain_id=\"namada.5f5de2dd1b88cba30586420\"}" }}{{ printf "%.0f" (. | first | value) }}{{ end }}
        Chain id: {{ $labels.chain_id }}


  - alert: WhaleTransactionDetected
    expr: |
        transfer_amount{chain_id="namada.5f5de2dd1b88cba30586420"} > 10 * quantile(0.50, avg_over_time(transfer_amount{chain_id="namada.5f5de2dd1b88cba30586420"}[7d])) by (token)
        #### 2 std dev from
    labels:
      severity: warning
    annotations:
      summary: "Potential Whale Detected in {{ $labels.token }}"
      description: |
        A large transfer was detected in {{ $labels.token }}.
        Transfer Amount: {{ $value }} {{ $labels.token }}
        This exceeds 2x the median transfer amount in the last 7 days.
        Block height: {{ with query "namada_block_height{chain_id=\"namada.5f5de2dd1b88cba30586420\"} " }}{{ printf "%.0f" (. | first | value) }}{{ end }}
        Chain id: {{ $labels.chain_id }}

  - alert: HighSlashingRate
    expr: |
      slashes{chain_id="namada.5f5de2dd1b88cba30586420"} > 0
    labels:
      severity: critical
    annotations:
      summary: "Unusual number of validator slashes"
      description: |
        The slashing rate is abnormally high—more than twice the median of the last 7 days.
        This could indicate a network issue or malicious behavior. 
        Block height: {{ with query "namada_block_height{chain_id=\"namada.5f5de2dd1b88cba30586420\"}" }}{{ printf "%.0f" (. | first | value) }}{{ end }}
        Chain id: {{ $labels.chain_id }}
