groups:
- name: namada-validator-alerts
  rules:
  - alert: NamadaBlockHeightStalled
    expr: increase(namada_block_height{ chain_id="$$CHAIN_ID$$" }[1m]) == 0
    labels:
      severity: critical
    annotations:
      summary: "Namada block height is not increasing"
      description: |
          Validators appear to be stalled as the block height has not increased for 1 minute! 
          Last recorded block height: {{ with query "namada_block_height{chain_id=\"$$CHAIN_ID$$\"}" }} {{ printf "%.0f" (. | first | value)}}{{ end }}

  - alert: NamadaBlockProcessingSlow
    expr: |
      (
        avg_over_time(namada_block_time_sum{chain_id="$$CHAIN_ID$$"}[5m]) 
        / avg_over_time(namada_block_time_count{chain_id="$$CHAIN_ID$$"}[5m])
      ) 
      > 
      (
        avg_over_time(namada_block_time_sum{chain_id="$$CHAIN_ID$$"}[1w]) 
        / avg_over_time(namada_block_time_count{chain_id="$$CHAIN_ID$$"}[1w])
      ) 
      + 
      (
        2 * (
          stddev_over_time(namada_block_time_sum{chain_id="$$CHAIN_ID$$"}[1w]) 
          / avg_over_time(namada_block_time_count{chain_id="$$CHAIN_ID$$"}[1w])
        )
      )
    labels:
      severity: warning
    annotations:
      summary: "Namada block processing time is abnormal"
      description: |
        The average block processing time in the last 5 minutes is significantly higher than normal. 
        Current 5-minute average block time: {{ with query "(avg_over_time(namada_block_time_sum{chain_id=\"$$CHAIN_ID$$\"}[5m]) / avg_over_time(namada_block_time_count{chain_id=\"$$CHAIN_ID$$\"}[5m]))" }}{{ printf "%ds" (. | first | value) }}{{ end }}
        Expected to be below: {{ with query "avg_over_time(namada_block_time_sum{chain_id=\"$$CHAIN_ID$$\"}[1w]) / avg_over_time(namada_block_time_count{chain_id=\"$$CHAIN_ID$$\"}[1w]) + (2 * (stddev_over_time(namada_block_time_sum{chain_id=\"$$CHAIN_ID$$\"}[1w]) / stddev_over_time(namada_block_time_count{chain_id=\"$$CHAIN_ID$$\"}[1w])))" }}{{ printf "%ds" (. | first | value) }}{{ end }}
        Block height: {{ with query "namada_block_height{chain_id=\"$$CHAIN_ID$$\"}" }}{{ printf "%.0f" (. | first | value) }}{{ end }}

  - alert: NamadaVotingPowerConcentration
    expr: namada_one_third_threshold{ chain_id="$$CHAIN_ID$$" } > 0.6 * namada_two_third_threshold{ chain_id="$$CHAIN_ID$$" }
    labels:
      severity: critical
    annotations:
      summary: "Voting power is too concentrated"
      description: |
        The number of validators needed for 1/3 of the voting power is greater than 60% of the number of validators neededed for 2/3 voting power. 
        Block height: {{ with query "namada_block_height{ chain_id=\"$$CHAIN_ID$$\" }" }}{{ printf "%.0f" (. | first | value)}}{{ end }}

  - alert: NamadaLowValidatorParticipation
    expr: namada_one_third_threshold{ chain_id="$$CHAIN_ID$$" } < 1 or namada_two_third_threshold{ chain_id="$$CHAIN_ID$$" } < 1
    labels:
      severity: critical
    annotations:
      summary: "Very low validator participation detected"
      description: |
        The number of validators needed for 1/3 or 2/3 consensus is at zero, which indicates a potential network failure. 
        Block height: {{ with query "namada_block_height{ chain_id=\"$$CHAIN_ID$$\" }" }}{{ printf "%.0f" (. | first | value)}}{{ end }}

  - alert: NamadaAbnormalBonding
    expr: rate(namada_bonds_per_epoch{ chain_id="$$CHAIN_ID$$" }[10m]) > 1.5 * avg_over_time(namada_bonds_per_epoch{ chain_id="$$CHAIN_ID$$" }[7d])
    labels:
      severity: warning
    annotations:
      summary: "Unusual increase in bonding activity"
      description: |
        Bonding per epoch has increased significantly over the last 10 minutes compared to the average of last 7 days. 
        Block height: {{ with query "namada_block_height{ chain_id=\"$$CHAIN_ID$$\" }" }}{{ printf "%.0f" (. | first | value)}}{{ end }}

  - alert: NamadaAbnormalUnbonding
    expr: rate(namada_unbonds_per_epoch{ chain_id="$$CHAIN_ID$$" }[10m]) > 1.5 * avg_over_time(namada_unbonds_per_epoch{ chain_id="$$CHAIN_ID$$" }[7d])
    labels:
      severity: warning
    annotations:
      summary: "Unusual increase in unbonding activity"
      description: |
        Unbonding per epoch has increased significantly over the last 10 minutes compared to the average of last 7 days.
        Block height: {{ with query "namada_block_height{ chain_id=\"$$CHAIN_ID$$\" }" }}{{ printf "%.0f" (. | first | value)}}{{ end }}

  - alert: NamadaTransactionBatchSpike
    expr: |
      rate(namada_transaction_batch_size_count{ chain_id="$$CHAIN_ID$$" }[10m]) > (2 * quantile(0.50, rate(namada_transaction_batch_size_count[7d])))
    labels:
      severity: warning
    annotations:
      summary: "Spike in transaction batch size"
      description: |
        Transaction batching has significantly increased over the last 10 minutes compared to the 7-day median. 
        Block height: {{ with query "namada_block_height{ chain_id=\"$$CHAIN_ID$$\" }" }}{{ printf "%.0f" (. | first | value)}}{{ end }}
        
  - alert: HighTransactionFees
    expr: |
      (sum by (token) (namada_fees{chain_id="$$CHAIN_ID$$"})) > (sum by (token) (avg_over_time(namada_fees{chain_id="$$CHAIN_ID$$"}[10m]))) +  2 * (sum by (token) (stddev_over_time(namada_fees{chain_id="$$CHAIN_ID$$"}[10m])))
    labels:
      severity: warning
    annotations:
      summary: "Namada transaction fees have spiked"
      description: |
        The transaction fees in Namada have increased significantly beyond normal levels.
        Current fees: {{ with query "sum by (token) (namada_fees{chain_id=\"$$CHAIN_ID$$\"})" }}{{ printf "%.2f" (. | first | value) }}{{ end }}
        Expected normal range (10-minute avg + 2x std deviation): {{ with query "(sum by (token) (avg_over_time(namada_fees{chain_id=\"$$CHAIN_ID$$\"}[10m]))) + 2 * (sum by (token) (stddev_over_time(namada_fees{chain_id=\"$$CHAIN_ID$$\"}[10m])))" }}{{ printf "%.2f" (. | first | value) }}{{ end }}

  - alert: AbnormalInnerTransactionFailureRate
    expr: |
      (rate(namada_transaction_kind{chain_id="$$CHAIN_ID$$", failed="true"}[10m]) / rate(namada_transaction_kind{ chain_id="$$CHAIN_ID$$" }[10m]))
      >
      (2 * quantile(0.50, rate(namada_transaction_kind{chain_id="$$CHAIN_ID$$", failed="true"}[7d:]) / rate(namada_transaction_kind{chain_id="$$CHAIN_ID$$"}[7d:])))
    labels:
      severity: critical
    annotations:
      summary: "Unusual spike in inner transaction failures"
      description: |
        The failure rate of inner transactions has spiked abnormally compared against the median in the last 7 days.
        Block height: {{ with query "namada_block_height{chain_id=\"$$CHAIN_ID$$\"}" }}{{ printf "%.0f" (. | first | value) }}{{ end }}
        Current failure rate: {{ with query "rate(namada_transaction_kind{chain_id=\"$$CHAIN_ID$$\", failed=\"true\"}[10m])" }}{{ printf "%.2f" (. | first | value)}}{{ end }}

  - alert: WhaleTransactionDetected
    expr: |
        increase(namada_transfer_amount{chain_id="$$CHAIN_ID$$"}[1m]) > 
        avg_over_time(increase(namada_transfer_amount{chain_id="$$CHAIN_ID$$"}[1w])[1w:1m])
    labels:
      severity: warning
    annotations:
      summary: "Potential Whale Detected in {{ $labels.token }}"
      description: |
        Token {{ $labels.token }} experienced a large transfer in last minute ({{ with query "increase(namada_transfer_amount{chain_id=\"$$CHAIN_ID$$\"}[1m])" }}{{ printf "%.0f" (. | first | value) }}{{ end }})
        The amount is unusually high compared to the typical increases over the past week.
        Transfer Amount: {{ $value }} {{ $labels.token }}
        Block height: {{ with query "namada_block_height{chain_id=\"$$CHAIN_ID$$\"} " }}{{ printf "%.0f" (. | first | value) }}{{ end }}

  - alert: HighSlashingRate
    expr: |
      slashes{chain_id="$$CHAIN_ID$$"} > 0
    labels:
      severity: critical
    annotations:
      summary: "Unusual number of validator slashes"
      description: |
        Slashing detected.
        Block height: {{ with query "namada_block_height{chain_id=\"$$CHAIN_ID$$\"}" }}{{ printf "%.0f" (. | first | value) }}{{ end }}
       
  - alert: AbnormalConsensusValidatorChange
    expr: |
      (
        abs(namada_consensus_validators{chain_id="$$CHAIN_ID$$"}
        - avg_over_time(namada_consensus_validators{chain_id="$$CHAIN_ID$$"}[7d]))
      ) > (2 * stddev_over_time(namada_consensus_validators{chain_id="$$CHAIN_ID$$"}[7d]))
    labels:
      severity: warning
    annotations:
      summary: "Abnormal increase/decrease in consensus validators"
      description: |
        The number of validators in the consensus state has increased/decreased abnormally.
        Block height: {{ with query "namada_block_height{chain_id=\"$$CHAIN_ID$$\"}" }}{{ printf "%.0f" (. | first | value) }}{{ end }}

  - alert: AbnormalInactiveValidatorIncrease
    expr: |
      (
        namada_inactive_validators{chain_id="$$CHAIN_ID$$"}
        - avg_over_time(namada_inactive_validators{chain_id="$$CHAIN_ID$$"}[7d])
      ) > (2 * stddev_over_time(namada_inactive_validators{chain_id="$$CHAIN_ID$$"}[7d]))
    labels:
      severity: warning
    annotations:
      summary: "Abnormal increase in inactive validators"
      description: |
        The number of inactive validators has increased abnormally.
        Block height: {{ with query "namada_block_height{chain_id=\"$$CHAIN_ID$$\"}" }}{{ printf "%.0f" (. | first | value) }}{{ end }}

  - alert: AbnormalJailedValidatorIncrease
    expr: |
      (
        namada_jailed_validators{chain_id="$$CHAIN_ID$$"}
        - avg_over_time(namada_jailed_validators{chain_id="$$CHAIN_ID$$"}[7d])
      ) > (2 * stddev_over_time(namada_jailed_validators{chain_id="$$CHAIN_ID$$"}[7d]))
    labels:
      severity: critical
    annotations:
      summary: "Abnormal increase in jailed validators"
      description: |
        The number of jailed validators has increased abnormally.
        Block height: {{ with query "namada_block_height{chain_id=\"$$CHAIN_ID$$\"}" }}{{ printf "%.0f" (. | first | value) }}{{ end }}


  - alert: AbnormalBelowThresholdValidatorIncrease
    expr: |
      (
        namada_below_threshold_validators{chain_id="$$CHAIN_ID$$"}
        - avg_over_time(namada_below_threshold_validators{chain_id="$$CHAIN_ID$$"}[7d])
      ) > (2 * stddev_over_time(namada_below_threshold_validators{chain_id="$$CHAIN_ID$$"}[7d]))
    labels:
      severity: warning
    annotations:
      summary: "Abnormal increase in below-threshold validators"
      description: |
        The number of validators below the threshold has increased abnormally.
        Block height: {{ with query "namada_block_height{chain_id=\"$$CHAIN_ID$$\"}" }}{{ printf "%.0f" (. | first | value) }}{{ end }}

  - alert: AbnormalBelowCapacityValidatorIncrease
    expr: |
      (
        namada_below_capacity_validators{chain_id="$$CHAIN_ID$$"}
        - avg_over_time(namada_below_capacity_validators{chain_id="$$CHAIN_ID$$"}[7d])
      ) > (2 * stddev_over_time(namada_below_capacity_validators{chain_id="$$CHAIN_ID$$"}[7d]))
    labels:
      severity: warning
    annotations:
      summary: "Abnormal increase in below-capacity validators"
      description: |
        The number of validators below capacity has increased abnormally.
        Block height: {{ with query "namada_block_height{chain_id=\"$$CHAIN_ID$$\"}" }}{{ printf "%.0f" (. | first | value) }}{{ end }}
