global:
  scrape_interval: 10s
scrape_configs:
 - job_name: namada
   fallback_scrape_protocol: PrometheusText0.0.4
   static_configs:
    - targets:
       - monitoring:9184    # monitoring is the composer name in the docker composer spec
rule_files:
  - "namada-alerts-$$CHAIN_ID$$.yml"  # It should be at folder /etc/prometheus/
