
services:
  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    command:
      - --storage.tsdb.retention.time=30d
    ports:
      - 9090:9090
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
      - "./namada-alerts.yml:/etc/prometheus/namada-alerts.yml"
      
  monitoring:
    image: namada/monitoring
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: --rpc http://$EXTIP:$RPC_PORT  --chain-id $CHAIN_ID
    ports:
      - 9184:9184
