{
 "title": "Namada Monitoring Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Voting power",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namada_total_voting_power / namada_total_supply_native_token",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocks Produced In 10 Minutes",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(namada_block_height[10m])",
     "legendFormat": "Block Height"
    }
   ]
  },
  {
   "title": "Avg Block Processing Time(secs)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 10, "x": 9, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(namada_block_time_sum[1m]) / rate(namada_block_time_count[1m]) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Epoch Increase",
   "type": "stat",
   "gridPos": { "h": 3, "w": 19, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "namada_epoch", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Bonds/(Bond+Unbonds)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namada_bonds / (namada_bonds + namada_unbonds)",
     "legendFormat": "Bonds/Unbonds"
    }
   ]
  },
  {
   "title": "Voting concentration",
   "type": "gauge",
   "description": "namada_one_third_threshold/namada_two_third_threshold",
   "gridPos": { "h": 7, "w": 9, "x": 10, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namada_one_third_threshold/namada_two_third_threshold",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction Fees",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(namada_fees) by (token)", "legendFormat": "Fees - {{token}}" }
   ]
  },
  {
   "title": "Total Supply of Native Token",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 10, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "namada_total_supply_native_token",
     "legendFormat": "Total Supply"
    }
   ]
  }
 ]
}